name: Python CI

on:
  push:
    branches: [ main ]  # Écoute les changements sur la branche main
  pull_request:
    branches: [ main ]  # Exécute les tests lors des pull requests vers main

jobs:
  build:
    runs-on: ubuntu-latest  # Exécute sur une machine virtuelle Ubuntu

    steps:
    - uses: actions/checkout@v3  # Vérifie le code du dépôt
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Spécifie la version de Python à utiliser
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Installe les dépendances
    - name: Run tests
      run: pytest  # Exécute les tests avec pytest
